### PR TITLE
Ensure Binder validates after TextField validation

### LINKED ISSUE #257: vaadin-text-field doesn't show validation error on eager mode
TextField doesn't show validation error on eager mode anymore,
since moving the validation to server side vaadin 14.0.5 -> 14.0.6 (https://github.com/vaadin/vaadin-text-field-flow/pull/213)

the vaadin-text-field html tag attribute _invalid_ is not set after validation fails,
and so the css for showing the error message is not active.

### PR DESCRIPTION
**Pull request by pekam**
By adding a ValueChangeListener in constructor, we can ensure that the
component's own server-side validation logic runs before Binder's
validation.

Binder validation still can't take component's validation into account.
A new feature is required for both validations to work together:
vaadin/flow#6803

Fix #257

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/261)

### CODE REVIEW

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java [hunk 1]
```diff
@@ -450,12 +452,6 @@ public String getValue() {
         return super.getValue();
     }
 
-    @Override
-    protected void setModelValue(String newModelValue, boolean fromClient) {
-        super.setModelValue(newModelValue, fromClient);
-        setInvalid(getValidationSupport().isInvalid(newModelValue));
```
Comment (pekam) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java]: The problem with this approach was, that the `super.setModelValue` triggers all the `ValueChangeListener`s. One of those is added by Binder to run the validation. The component's own server-side validation runs after that, on the second line.

Another problem was, that this `setModelValue` can execute also when the old value is equal to the new value.

File: vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+public class BinderValidationPage extends Div {
+
+    private Binder<Bean> binder = new Binder<>(Bean.class);
+
+    public static final String BINDER_ERROR_MSG = "binder";
+
+    public BinderValidationPage() {
+
+        addComponent(new TextField(), Bean::getString, Bean::setString,
+                value -> value.length() > 2, field -> field.setMinLength(1));
```
Comment (tomivirkki) [inline vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: If i change this condition to `value.length() == 0 || value.length() > 2` the field doesn't get re-validated once it's invalid and then emptied.

Comment (pekam) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: I would assume it's because `TextField`'s empty value is `null`.

Comment (pekam) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: Sorry, no it's not. I'll investigate more.

Comment (pekam) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: It comes from here: https://github.com/vaadin/vaadin-text-field-flow/blob/3f30431ef704aa5816c83d72dcd5955ae4d1b362/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java#L56-L61

When the field is empty, the client validation says it's valid.

Looks like we have to consider what to do with client-side validation at this point. We could try to rearrange the listeners so that this runs before the Binder validation. But this listener is still dangerous. If the invalid-property changes at client-side it will revalidate only based on the component's internal validation, since it doesn't know about Binder. Maybe we should not synchronize the invalid-property on `invalid-changed` at all. Also, maybe we should always disable client-side validation for Flow components and handle everything at server-side (like in V8).

Comment (pekam) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: Great catch btw!

Comment (yuriy-fix) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: One more update: there seems to be a problem with re-validation on blurring.

Steps:
- Focus the field
- Type two characters (i.e. `11`)
- Press Enter (value is applied and `binder` error message is shown)
- Blur the field (it's revalidated and the error-message is hidden)

valdiation

Comment (pekam) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: Oh man. When you hit Enter, it sends the value-changed-event and validates at server-side. When you blur, I guess the web component runs validation also then. But the value has not changed, so there's nothing triggering server-side validation.

Sounds like one more reason to always disable client-side validation. It's too hard to keep the validation logics in sync. And the client doesn't know about Binder validators, so that happens anyway after a roundtrip. Maybe it would be best to always do validation after a roundtrip.

Comment (pekam) [reply vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/BinderValidationPage.java]: Sorry, it actually runs the server-side validation, because of the invalid-changed. But in that case it validates only by the component's logic (minlength=2)

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java [hunk 3]
```diff
@@ -94,12 +94,10 @@ public AbstractNumberField(SerializableFunction<String, T> parser,
...
-        addInvalidChangeListener(e -> {
-            // If invalid is updated from client to false, check it
-            if (e.isFromClient() && !e.isInvalid()) {
-                validate();
-            }
-        });
+
+        addAttachListener(e -> getElement()
+                .executeJs("$0.validate = function () {return this.checkValidity();}",
+                        getElement()));
```
Comment (pekam) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java]: Can we now remove everything related to the `RequiredValidationUtil` (the helper class to disable client validation in some cases, inside text-field-flow repo)?

Comment (pekam) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java]: Maybe this should be extracted as a static method somewhere? Maybe in a helper class, eg.
```java
TextFieldValidationUtil.disableClientValidation(Component field)`
```
(the class should be package protected in this case)

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java [hunk 4]
```diff
@@ -705,7 +705,6 @@ protected void setRequired(boolean required) {
      *
      * @return the {@code invalid} property from the webcomponent
      */
-    @Synchronize(property = "invalid", value = "invalid-changed")
```
[the remark this answers is not in the document]
Comment (yuriy-fix) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java]: It was done in all that were synced.

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+
+    static void disableClientValidation(Component component) {
+        execJS(component,
+                "$0.validate = function () {return this.checkValidity();}");
+    }
+
+    private static void execJS(Component component, String js) {
+        StateNode node = component.getElement().getNode();
+
+        node.runWhenAttached(ui -> ui.getInternals().getStateTree()
```
[the remark this answers is not in the document]
Comment (yuriy-fix) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java]: Updated.

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+                .beforeClientResponse(node, context ->
+                        ui.getPage().executeJs(js, component.getElement())
```
[the remark this answers is not in the document]
Comment (yuriy-fix) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java]: Updated.

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (pekam) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java]: Doesn't look like. `disableClientValidation` should add attach listener

[the remark this answers is not in the document]
Comment (pekam) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/fieldValidationUtil.java]: It should also check if it's currently attached, and in that case run the JS immediately.

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/FieldValidationUtil.java [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+        // if the component was already attached override the validate()
+        overrideClientValidation(component);
+
+        component.addAttachListener(e -> overrideClientValidation(component));
+    }
+
+    private static void overrideClientValidation(Component component) {
+        PendingJavaScriptResult javaScriptResult =
+                component.getElement()
+                        .executeJs("$0.validate = function () {return this.checkValidity();}",
```
Comment (tomivirkki) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/FieldValidationUtil.java]: nit: There shouldn't be a need to use parameters here. `this` defaults to the element instance you call the `executeJs` on. Same thing in the other `executeJs` few lines below
