### PR TITLE
Fix RTL styles for big decimal field

### LINKED ISSUE #302: Numeric fields must enter from left to right
Entering numeric values in fields like Decimal fields and Integer fields should be from left to right instead of right to left.

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes #302 
Requires https://github.com/vaadin/vaadin-text-field/pull/470

### CODE REVIEW

File: vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js [hunk 1]
```diff
@@ -29,6 +29,41 @@
...
+                  }
+
+                  :host([dir="rtl"]:not([has-controls])) [part="value"]:-ms-input-placeholder,
+                  :host([dir="rtl"]:not([has-controls])) [part="input-field"] ::slotted(input):-ms-input-placeholder {
+                    text-align: left;
+                  }
+
+                  :host([dir="rtl"]) [part="value"],
+                  :host([dir="rtl"]) [part="input-field"] ::slotted(input) {
+                    --_lumo-text-field-overflow-mask-image: linear-gradient(to left, transparent, #000 1.25em);
```
Comment (DiegoCardoso) [inline vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js:65]: This style is getting overridden by the default one for RTL because it's being placed before it:
Screenshot 2020-05-04 at 10 57 37

This is how it looks like:
Screenshot 2020-05-04 at 10 58 19
