### PR TITLE
Set initial value only if element has no property value

### LINKED ISSUE #349: TextField CTOR is unaware of possibly already existing  "value" property in underlying Element.
This is failing test:

```
Element element = new Element("vaadin-text-field");
        element.setProperty("value", "foo");
        UI ui = new UI();
        UI.setCurrent(ui);
        VaadinSession session = Mockito.mock(VaadinSession.class);
        ui.getInternals().setSession(session);
        VaadinService service = Mockito.mock(VaadinService.class);
        Mockito.when(session.getService()).thenReturn(service);

        Instantiator instantiator = Mockito.mock(Instantiator.class);

        Mockito.when(service.getInstantiator()).thenReturn(instantiator);

        Mockito.when(instantiator.createComponent(TextField.class))
                .thenAnswer(a -> new TextField());
        TextField field = Component.from(element, TextField.class);
        Assert.assertEquals("foo", field.getValue());
```

There is a PR which sets the value based on the underlying Element property `value`: https://github.com/vaadin/flow/pull/9031
But `TextField`  uses a CTOR which provides an initial value which just overrides the value set by `AbstractSinglePropertyField`.
This needs to be fixed.
The detailed explanation is here: https://github.com/vaadin/flow/issues/9012#issuecomment-694810632

The same bug is all over the any component which implements `AbstractSinglePropertyField`. 
So every such component should be fixed.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #349

### CODE REVIEW

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java [hunk 1]
```diff
@@ -63,6 +63,14 @@
...
     /**
      * Sets up the common logic for number fields.
+     * <p>
+     * If {@code isInitialValueOptional} is {@code true} then the initial value
+     * is used only if element has no {@code "value"} property value, otherwise
+     * element {@code "value"} property is ignored and the initial value is set.
+     * <p>
+     * If {@code isInitialValueOptional} is {@code true} then the initial value
+     * is used only if element has no {@code "value"} property value, otherwise
+     * element {@code "value"} property is ignored and the initial value is set.
```
Comment (mshabarov) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java:73]: This paragraph is repeated two times, remove one

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java [hunk 2]
```diff
@@ -98,6 +112,32 @@ public AbstractNumberField(SerializableFunction<String, T> parser,
         FieldValidationUtil.disableClientValidation(this);
     }
 
+    /**
+     * Sets up the common logic for number fields.
+     * <p>
+     * If {@code isInitialValueOptional} is {@code true} then the initial value
```
Comment (mshabarov) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java:118]: Delete this paragraph, because this CTOR has no such a parameter

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java [hunk 3]
```diff
@@ -954,8 +954,8 @@ protected void removeAll() {
             SerializableFunction<T, P> modelToPresentation) {
         super("value", defaultValue, elementPropertyType, presentationToModel,
                 modelToPresentation);
-        if (initialValue != null) {
-            setModelValue(initialValue, false);
+        if (getElement().getPropertyRaw("value") == null
```
Comment (mshabarov) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java:957]: Don't need `getElement().getPropertyRaw("value") == null` ?

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java [hunk 4]
```diff
@@ -98,6 +115,7 @@ public TextArea(String label, String placeholder) {
      */
     public TextArea(String label, String initialValue, String placeholder) {
         this(label);
+        setLabel(label);
```
Comment (mshabarov) [inline vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java:118]: Why? Label is assigned within `this(label)`

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java (hunk 3 above)
Comment (denis-anisimov) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java:957]: Leftover, thanks.

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java (hunk 4 above)
Comment (denis-anisimov) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextArea.java:118]: Leftover.

File: vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java (hunk 1 above)
Comment (mshabarov) [reply vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java:73]: Still have this one paragraph duplicated. Note that it's not about CTOR description and param description duplication. It's about the same text duplicated 2 times in the CTOR description.

File: vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java [hunk 5]
```diff
@@ -76,21 +76,21 @@ public void fields_internalValidationPass_binderValidationFail_fieldInvalid() {
 
     @Test
     public void fields_internalValidationPass_binderValidationFail_validateClient_fieldInvalid() {
-        fieldClasses.forEach(clazz -> {
```
Comment (mshabarov) [inline vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java:79]: Why did you change that test to be applied only for TextArea?

Comment (denis-anisimov) [reply vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/BinderValidationPageIT.java:79]: Temp changes. Test is bad because doesn't say which component failed.
Had to detect it and check only `TextArea`.

Reverted, thanks.

**Review by mshabarov — APPROVED** [review]
